name: covid_data_bot_post_scheduled

on: 
  schedule:
    - cron: '*/10 * * * *'

jobs:
  covid_data_bot-post:
    runs-on: macOS-latest
    env:
      TWITTER_CONSUMER_API_KEY: ${{ secrets.TWITTER_CONSUMER_API_KEY }}
      TWITTER_CONSUMER_API_SECRET: ${{ secrets.TWITTER_CONSUMER_API_SECRET }}
      TWITTER_ACCESS_TOKEN: ${{ secrets.TWITTER_ACCESS_TOKEN }}
      TWITTER_ACCESS_TOKEN_SECRET: ${{ secrets.TWITTER_ACCESS_TOKEN_SECRET }}
      MAPBOX_PUBLIC_ACCESS_TOKEN: ${{ secrets.MAPBOX_PUBLIC_ACCESS_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - name: Create and post tweet
        run: Rscript covid_data_bot_v1.R
      - name: Commit and push previous tweets
        run: |
          git config user.name actions-user
          git config user.email "actions@github.com"
          git add previous_tweets.csv
          git commit --allow-empty -m "update previous tweets file"
          git push